version: '3'

services:
  
  teamcity_server:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    container_name: teamcity-server-instance
    volumes:
      - ~/teamcity/data:/data/teamcity_server/datadir
      - ~/teamcity/teamcity/logs:/opt/teamcity/logs
    ports:
    - "8111:8111"    
      
  teamcity_agent:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    privileged: true
    container_name: teamcity-agent-instance
    environment:
      - DOCKER_IN_DOCKER=start
    volumes:
      - ./servers/teamcity/agent/conf:/data/teamcity_agent/conf
        
      

