version: '3'

services:
  
  teamcity_server:
    image: "jetbrains/teamcity-server"
    container_name: teamcity-server-instance
    volumes:
      - ~/TeamCity/data:/data/teamcity_server/datadir
      - ~/TeamCity/logs:/opt/teamcity/logs
    ports:
    - "8111:8111"    
      
  teamcity_agent:
    image: jetbrains/teamcity-agent
    container_name: teamcity-agent-instance
    environment:
      - SERVER_URL="http://teamcity_server:8111"      
      - DOCKER_IN_DOCKER=start
    volumes:
      - ~/TeamCity/agent/conf:/data/teamcity_agent/conf
      

